# Generated by Django 4.1.2 on 2022-11-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(default='https://picsum.photos/id/532/800/500'),
        ),
    ]
